# Generated by Django 4.2.5 on 2023-10-06 12:42

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
